spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/infytel-customer
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      
customer:
  name: m sathya kumar reddy

friend:
  uri: http://localhost:8200/

plan:
  uri: http://localhost:8100/
